### ISSUE TITLE
Code orginization

### ISSUE THREAD

**Issue by tkaitchuck** [jlmucb/cloudproxy#1]
According to https://golang.org/doc/code.html
go code needs to go under the src directory. Here it is under the go/ subdirectory. This breaks go IDEs which assume the standard path layout. (notably goclipse has no way to work with this.)

**Comment by tmroeder** [comment]
AFAICT, this code satisfies those requirements. Notice that the src directory in the requirements is under $GOPATH. And if you do `go get github.com/jlmucb/cloudproxy/go/...`, it produces the directory github.com/jlmucb/cloudproxy/ under $GOPATH/src, as expected.
