### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by tkaitchuck** [jlmucb/cloudproxy#3]
There are several steps missing in the install instructions.
So far: 
You need to install go, re2c, and a few go libraries.
set the GOPATH environment variable. 
After doing both of these I was still getting build failures until I ran:
cmake -DCMAKE_BUILD_TYPE=Debug
WHITHOUT
-G Ninja

It does not seem to understand that flag.

**Comment by jethrogb** [comment]
Worked for me after installing ninja-build natively (i.e. not from the third_party directory).

**Comment by tkaitchuck** [comment]
Confirmed. (Although it still builds it in 3rd party)

**Comment by tkaitchuck** [comment]
The libvirt error is fixed by installing libvirt-dev

**Comment by jethrogb** [comment]
See also #4

**Comment by tkaitchuck** [comment]
The unit test instructions also assume the existence of ./out/Release/bin/tao_test
which is not created in any previous step, (And I can't figure out how to get) 
as well as assuming that some portions of the source tree have been dumped directly in your home directory...

**Comment by jethrogb** [comment]
A lot of stuff has been removed in 7a5a30b, maybe you can find what you need in d2a72d9.

**Comment by tkaitchuck** [comment]
That does get further. If I run src/build/unittests.sh 
I get the following:

Unit test working directory: /usr/local/google/home/tkaitchuck/unittest
F0610 15:11:46.763111  1085 tpm_tao.cc:66] Check failed: tao->Init() 
*** Check failure stack trace: ***
    @           0x4dfdf3  google::LogMessage::Fail()
    @           0x4dfd46  google::LogMessage::SendToLog()
    @           0x4df6ef  google::LogMessage::Flush()
    @           0x4e26a8  google::LogMessageFatal::~LogMessageFatal()
    @           0x482364  main
    @     0x7f59fa2a7ec5  (unknown)
    @           0x481d99  (unknown)
    @              (nil)  (unknown)
./build/unittests.sh: line 69:  1085 Aborted                 (core dumped) $bin/tpm_tao -path $tpm -create

Running src/out/Debug/bin/tao_test directly gets a bunch of tests to run, but all taotest/ ones fail for me.

**Comment by jlmucb** [comment]
By an odd coincidence, someone else pointed some of this out today.  We'll
try to fix this.

Thanks.
