### ISSUE TITLE
Start linux_host's hosted programs with tao_launch's controlling terminal

### ISSUE THREAD

**Issue by jethrogb** [jlmucb/cloudproxy#8]
Currently, when starting programs with tao_launch, the hosted program is attached to linux_host's controlling terminal. This means if you want to communicate with the hosted program over stdin/stdout/stderr, you'll have to switch to linux_host's terminal. Additionally, that terminal might no longer exist.

See also #7.

**Comment by kevinawalsh** [comment]
There is a pending pull request for redirecting stdio to tao_launch's terminal. It only redirects stdio, however, and does not change the controlling terminal. That feature appears to be impossible, or at least very difficult and reliant on a lot of obscure and fragile linux-specific hacks. There just doesn't seem to be a clean way to attach an arbitrary process to an arbitrary controlling terminal. Go read about process sessions and session leaders, process groups and group leaders, reptyr, etc.

**Comment by jethrogb** [comment]
Maybe you can create the illusion by redirecting stdio and keeping tao_launch alive as long as the hosted program?

**Comment by kevinawalsh** [comment]
Sure, that's doable. It would behave kind of like "ssh" does, I suppose.

**Comment by kevinawalsh** [comment]
Fixed by 828d660...40f08df
